### ISSUE TITLE
Issue Using Imported Potions with Potion Planner (NaN)

### ISSUE THREAD

**Issue by joecrase** [duke605/botanists-assistant#1]
Hello! I have imported various potion ingredients / potions (both finished and unfinished) into the Planned Potions plugin. But when trying to use them by checking the box to Subtract potions from inventory the results show NaN

![image](https://github.com/user-attachments/assets/73e7a4a8-b91d-47d1-95b6-416e3f3cfe47)
![image](https://github.com/user-attachments/assets/50613293-d258-439e-831b-291b1f14fa8f)
![image](https://github.com/user-attachments/assets/b32fe55f-bdbe-48a1-85c0-3e782dcfbe2f)
![image](https://github.com/user-attachments/assets/98938d42-9de8-4e6c-91c7-8dbde62c431e)

When not using the option, it appears to show everything properly (though of course not taking into account what I already have)

![image](https://github.com/user-attachments/assets/b5efb567-9f3c-47a7-b7a5-23505c6357b7)
![image](https://github.com/user-attachments/assets/6ba85332-a398-4bab-8c2e-12eff5162b53)

**Comment by duke605** [comment]
Issue has been fixed. Thank you for submitting such a detailed report and congratulations (or I'm sorry) on being my first issue

PR: https://github.com/duke605/botanists-assistant/pull/3
