### ISSUE TITLE
Calculating Elder Overload Salves

### ISSUE THREAD

**Issue by joecrase** [duke605/botanists-assistant#5]
Hello! - I have been trying to make some elder overload salve potions with this calculator, and started to notice some strange maths seemingly going on with the settings I was using. 

I decided to do a no-bonuses or gear or anything calculation using this, as well as not using any existing supplies. 

I might be misunderstanding, but in the example below I queued up 500 elder overload salve potions. 

The first three entries look about right (at 500). But then for Overload, it is showing 667 4 dose overloads - and hence about 2668 doses. I would expect this to also be 500 4 dose overloads with around 2,000 doses. 

Below is screenshots with dose and no dose mode enabled to show more clearly

![image](https://github.com/user-attachments/assets/32e5f7e8-a61a-4feb-add4-f0004a8c9926)

![image](https://github.com/user-attachments/assets/36544750-54b0-49b1-9f5d-f9f9f0a63ce6)

I cross checked also on the wiki calculator with the same settings, and those results are as expected.

![image](https://github.com/user-attachments/assets/99eaffe0-fce8-4711-8b3e-027a345ef3d9)

![image](https://github.com/user-attachments/assets/a29cce01-615c-482b-9b74-2d777f20ffab)

**Comment by duke605** [comment]
Oof... You know... I compared my results to the wiki calc and forgot that the wiki showed (3) of overloads so when I got 667 (4) I thought they matched but they're different dosages 🤦‍♂️. Math has been corrected... I hope

Is it alright if I include your GitHub handle (@joecrase) in the changelog? I want to give you credit for catching this

**Comment by joecrase** [comment]
Yeah no problem!

**Comment by duke605** [comment]
Thanks! Credit has been given :)
